// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://amrorxnyoyxfvofticsr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtcm9yeG55b3l4ZnZvZnRpY3NyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEyMTg4OTksImV4cCI6MjA3Njc5NDg5OX0.hZkKXxrv35RFFt6y4C29wrl_1Rv3-jgSxkNs5436vdE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});